apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress-uri
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/health /health break;
spec:
  rules:
  #- host: testk8s.com
  - http:
      paths:
      - path: /home
        backend:
          serviceName: clusterip-test-name
          servicePort: 5000
      - path: /health 
        backend:
          serviceName: clusterip-test-name
          servicePort: 5000

