apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: python-app-uri
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: testk8s.com
    http:
      paths:
      - path: /health
        backend:
          serviceName: users-api
          servicePort: 4200
      - path: /home
        backend:
          serviceName: payments-api
          servicePort: 8080